{{- $values := merge dict .Values.ext .Values }}
{{- $pdns := merge dict .Values.pdns .Values }}
{{- $root := merge (dict "Values" $values "Release" .Release "Chart" .Chart) . }}
{{- range $values.namespaces }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "extpdns.fullname" $root }}-ext-{{ . }}
  labels:
    {{- include "extpdns.labels" $root | nindent 4 }}
spec:
{{- if not $values.autoscaling.enabled }}
  replicas: {{ $values.replicaCount }}
{{- end }}
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      {{- include "extpdns.selectorLabels" $root | nindent 6 }}
  template:
    metadata:
    {{- with $values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "extpdns.selectorLabels" $root | nindent 8 }}
    spec:
      {{- with $values.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      # Only use if you're also using RBAC
      serviceAccountName: {{ include "extpdns.serviceAccountName" $root }}
      securityContext:
        {{- toYaml $values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $root.Chart.Name }}-ext
          image: "{{ $values.image.repository }}:{{ $values.image.tag }}"
          imagePullPolicy: {{ $values.image.pullPolicy }}
          env:
          - name: EXTERNAL_DNS_PDNS_API_KEY
            valueFrom:
              secretKeyRef:
                name: {{ include "extpdns-persist.fullname" $root }}
                key: api-key
          args:
          # will make ExternalDNS see only the zones matching provided domain; omit to process all available zones in PowerDNS
          # note: cross-chart picking!
          - --interval={{ $values.interval }}
          - --domain-filter={{ join "\n" $pdns.zones | indent 12 | trim }}
          - --log-level={{ $values.logLevel }}
          #- --pdns-api-key=$(PDNS_API_KEY) # using env var
          - --pdns-server=http://{{ include "extpdns-pdns.fullname" $root }}-api:{{ $pdns.service.api.port }}
          - --provider=pdns
          {{- if $values.registry }}
          - --registry={{ $values.registry }}
          {{- end }}
          {{- range $values.source }}
          - --source={{ . }}
          {{- end }}
          - --txt-owner-id={{ $values.owner | default (include "extpdns.fullname" $root) }}
          securityContext:
            {{- toYaml $values.securityContext | nindent 12 }}
        {{- with $values.nodeSelector }}
        nodeSelector:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with $values.affinity }}
        affinity:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with $values.tolerations }}
        tolerations:
          {{- toYaml . | nindent 8 }}
        {{- end }}
{{ end }}
