apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "extpdns.fullname" . }}-config
  labels:
    {{- include "extpdns.labels" . | nindent 4 }}
data:
  # TODO supposed to be the edns nsid
  server-id: {{ include "extpdns.fullname" . }}
  gpgsql-host: {{ include "extpdns-persist.serviceName" . }}
  {{- range $key, $value := .Values.pdns.config }}
  {{ $key }}: "{{ $value }}"
  {{- end }}
