apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "extpdns.fullname" . }}-config
  labels:
    {{- include "extpdns.labels" . | nindent 4 }}
data:
  # TODO supposed to be the edns nsid
  server-id: {{ .Values.pdns.serverId | default (include "extpdns.fullname" .) }}
  gpgsql-host: {{ .Values.persist.pg.serviceName | default (include "extpdns-persist.fullname" .) }}
  gpgsql-port: "{{ .Values.persist.pg.port | default 5432 }}"
  gpgsql-dbname: {{ .Values.persist.pg.database | default "pdns_db" }}
  gpgsql-extra-connection-parameters: "appplication_name={{ .Values.pdns.pgAppName | default (include "extpdns.fullname" . ) }}"
  {{- range $key, $value := .Values.pdns.config }}
  {{ $key }}: "{{ $value }}"
  {{- end }}
