apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "extpdns.fullname" . }}-config
  labels:
    {{- include "extpdns.labels" . | nindent 4 }}
data:
  gpgsql-host: {{ include "extpdns-persist.fullname" . }}
  gpgsql-dbname: pdns
  launch: bind,gpgsql
  {{ range $key, $value := .Values.pdns }}
  {{ $key }}: "{{ $value }}"
  {{- end }}
