apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "extpdns.fullname" . }}-config
  labels:
    {{- include "extpdns.labels" . | nindent 4 }}
data:
  # TODO supposed to be the edns nsid
  server-id: {{ include "extpdns.fullname" . }}
  gpgsql-host: {{ .Values.persist.pg.serviceName | default (include "extpdns-persist.fullname" .) }}
  gpgsql-port: {{ .Values.persist.pg.port | default "5432" }}
  gpgsql-dbname: {{ .Values.persist.pg.database | default "pdns_db" }}
  {{- range $key, $value := .Values.pdns.config }}
  {{ $key }}: "{{ $value }}"
  {{- end }}
