apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "extpdns.fullname" . }}-config
  labels:
    {{- include "extpdns.labels" . | nindent 4 }}
data:
  sample: value
  {{- range $key, $value := .Values.pdns }}
  {{ $key }}: "{{ $value }}"
  {{- end }}
