{{- /* enhanced .Values with .Values.secret overlayed on top */ -}}
{{- $values := merge dict .Values.pdns .Values }}
{{- $root := merge (dict "Values" $values "Release" .Release) . }}
# {{ $values | toJson }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "extpdns.fullname" $root }}-pdns
  labels:
    {{- include "extpdns.labels" $root | nindent 4 }}
spec:
{{- if not $values.autoscaling.enabled }}
  replicas: {{ $values.replicaCount }}
{{- end }}
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      {{- include "extpdns.selectorLabels" $root | nindent 6 }}
  template:
    metadata:
    {{- with $values.podAnnotations }}
      annotations:
        {{- toYaml $root | nindent 8 }}
    {{- end }}
      labels:
        {{- include "extpdns.selectorLabels" $root | nindent 8 }}
    spec:
      {{- with $values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml $root | nindent 8 }}
      {{- end }}
      #serviceAccountName: {{ include "extpdns.serviceAccountName" $root }}
      securityContext:
        {{- toYaml $values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-pdns
          securityContext:
            {{- toYaml $values.securityContext | nindent 12 }}
          image: "{{ $values.image.repository }}:{{ $values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ $values.image.pullPolicy }}
          env:
            - name: PDNS_LAUNCH
              value: gpgsql
          volumeMounts:
            - name: etc-config
              mountPath: "/etc/powerdns/config"
              readOnly: true
            - name: etc-db
              mountPath: "/etc/powerdns/db"
              readOnly: true
            - name: etc-secret
              mountPath: "/etc/powerdns/secret"
              readOnly: true
          ports:
            - name: dns-udp
              containerPort: 53
              protocol: UDP
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
            {{- if hasKey $values.config "webserver-port" }}
            - name: webserver-api
              containerPort: {{ index $values.config "webserver-port" }}
              protocol: TCP
            {{- end }}
            {{ if hasKey $values.config "tcp-control-port" }}
            - name: tcp-control
              containerPort: {{ index $values.config "tcp-control-port" }}
              protocol: TCP
            {{- end }}
          livenessProbe:
            exec:
              command:
              - bash
              - -c
              - 'curl --fail -u#:$(cat /etc/powerdns/secret/webserver-password) http://localhost:{{ index $values.config "webserver-port" }}/metrics'
          readinessProbe:
            exec:
              command:
              - bash
              - -c
              - 'curl --fail -u#:$(cat /etc/powerdns/secret/webserver-password) http://localhost:{{ index $values.config "webserver-port" }}/metrics'
          resources:
            {{- toYaml $values.resources | nindent 12 }}
      volumes:
      - name: etc-config
        configMap:
          name: {{ include "extpdns.fullname" $root }}-config
      - name: etc-db
        secret:
          secretName: {{ include "extpdns-persist.db-owner" $root }}
          items:
          - key: username
            path: gpgsql-user
          - key: password
            path: gpgsql-password
      - name: etc-secret
        secret:
          secretName: {{ include "extpdns-persist.fullname" $root }}
      {{- with $values.nodeSelector }}
      nodeSelector:
        {{- toYaml $root | nindent 8 }}
      {{- end }}
      {{- with $values.affinity }}
      affinity:
        {{- toYaml $root | nindent 8 }}
      {{- end }}
      {{- with $values.tolerations }}
      tolerations:
        {{- toYaml $root | nindent 8 }}
      {{- end }}
