apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "extpdns.fullname" . }}-pdns
  labels:
    {{- include "extpdns.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "extpdns.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "extpdns.selectorLabels" . | nindent 8 }}
    spec:
      {{- with (.Values.pdns.image.pullSecrets | default .Values.images.pullSecrets) }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      #serviceAccountName: {{ include "extpdns.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-pdns
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.pdns.image.repository }}:{{ .Values.pdns.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.pdns.image.pullPolicy | default .Values.images.pullPolicy }}
          env:
            - name: PDNS_LAUNCH
              value: gpgsql
          volumeMounts:
            - name: etc-config
              mountPath: "/etc/powerdns/config"
              readOnly: true
            - name: etc-db
              mountPath: "/etc/powerdns/db"
              readOnly: true
            - name: etc-secret
              mountPath: "/etc/powerdns/secret"
              readOnly: true
          ports:
            - name: dns-udp
              containerPort: 53
              protocol: UDP
            - name: dns-tcp
              containerPort: 53
              protocol: TCP

            {{- if hasKey .Values.pdns.config "Webserver-port" }}
            - name: webserver-api
              containerPort: {{ index .Values.pdns.config "webserver-port" }}
              protocol: TCP
            {{- end }}
            {{ if hasKey .Values.pdns.config "tcp-control-port" }}
            - name: tcp-control
              containerPort: {{ index .Values.pdns.config "tcp-control-port" }}
              protocol: TCP
            {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: etc-config
        configMap:
          name: {{ include "extpdns.fullname" . }}-config
      - name: etc-db
        secret:
          secretName: {{ .Values.persist.db.user }}.{{ include "extpdns-persist.fullname" . }}{{ .Values.persist.db.suffix }}
          items:
          - key: username
            path: gpgsql-user
          - key: password
            path: gpgsql-password
      - name: etc-secret
        secret:
          secretName: {{ include "extpdns-persist.fullname" . }}
      {{- with (.Values.pdns.nodeSelector | default .Values.nodeSelector) }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (.Values.pdns.affinity | default .Values.affinity) }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (.Values.pdns.tolerations | default .Values.tolerations) }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
