apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: {{ include "external-dns-power-persist.fullname" . }}
  annotations:
    "helm.sh/resource-policy": {{ .Values.persist.resourcePolicy }}
  labels:
    {{- include "external-dns-power-persist.labels" . | nindent 4 }}
spec:
  teamId: "dns"
  volume:
    size: 192Mi
  numberOfInstances: 2
  users:
    admin: # database owner
    - superuser
    - createdb
    #pdns: []  # role for application foo
  databases:
    pdns: pdns_pdns_owner # dbname: owner
  preparedDatabases:
    pdns:
      schemas:
        pdns:
          defaultUsers: true
  postgresql:
    version: "12"
