apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: {{ include "extpdns-persist.fullname" . }}
  annotations:
    "helm.sh/resource-policy": {{ .Values.persist.resourcePolicy }}
  labels:
    {{- include "extpdns-persist.labels" . | nindent 4 }}
spec:
  teamId: "dns"
  volume:
    size: {{ .Values.persist.volumeSize }}
  numberOfInstances: {{ .Values.persist.postgresInstances }}
  users:
    admin:
      - superuser
      - createdb
    #pdns: []
  #databases:
  #  pdns: pdns
  preparedDatabases:
    pdns:
      schemas:
        pdns:
          defaultUsers: true
  postgresql:
    version: "12"
