{{- /* via https://github.com/helm/charts/issues/5167#issuecomment-641558251 */ -}}
{{- $key := (randAlpha 32) | b64enc | quote }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace (include "external-pdns-power-persist.fullname" .) }}
{{- if $secret }}
{{- $key = index $secret.data "pdns-api-key" }}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "external-dns-power-persist.fullname" . }}
  labels:
    {{- include "external-dns-power-persist.labels" . | nindent 4 }}
type: Opaque
data:
  pdns-api-key: {{ $key }}
