{{- /* enhanced Values with Values.secret overlayed on top */ -}}
{{- $values := merge dict .Values.persist .Values }}
{{- $root := merge (dict "Values" $values) . }}
{{- /* via https://github.com/helm/charts/issues/5167#issuecomment-641558251 */ -}}
{{- /* assume we need to generate keys */ -}}
{{- $api_key := (randAlpha 32) | b64enc | quote }}
{{- $tcp_control_secret := (randAlpha 32) | b64enc | quote }}
{{- $webserver_password := (randAlpha 32) | b64enc | quote }}
{{- /* lookup existing secrets here */ -}}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace (include "extpdns-persist.fullname" $root)) }}
{{- /* override our generated secrets with already known secrets */ -}}
{{- if $secret }}
{{- if hasKey $secret.data "api-key" }}{{ $api_key = index $secret.data "api-key" }}{{ end }}
{{- if hasKey $secret.data "tcp-control-secret" }}{{ $tcp_control_secret = index $secret.data "tcp-control-secret" }}{{ end }}
{{- if hasKey $secret.data "webserver-password" }}{{ $webserver_password = index $secret.data "webserver-password" }}{{ end }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "extpdns-persist.fullname" $root }}
  annotations:
    "helm.sh/resource-policy": {{ $values.resourcePolicy }}
  labels:
    {{- include "extpdns-persist.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ $api_key }}
  tcp-control-secret: {{ $tcp_control_secret }}
  webserver-password: {{ $webserver_password }}
  # if there's some better way i can pick this off the pg object lmk
  pg-schema: {{ $values.persist.pg.schema | default "pdns_schema" }}
  pg-database: {{ $values.persist.pg.database | default "pdns_db" }}
