{{- /* via https://github.com/helm/charts/issues/5167#issuecomment-641558251 */ -}}
{{- $api_key := (randAlpha 32) | b64enc | quote }}
{{- $tcp_control_secret := (randAlpha 32) | b64enc | quote }}
{{- $webserver_password := (randAlpha 32) | b64enc | quote }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace (include "extpdns-persist.fullname" .)) }}
{{- if $secret }}
{{- $api_key = index $secret.data "api-key" }}
{{- $tcp_control_secret = index $secret.data "tcp-control-secret" }}
{{- $webserver_password = index $secret.data "webserver-password" }}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "extpdns-persist.fullname" . }}
  annotations:
    "helm.sh/resource-policy": {{ .Values.persist.resourcePolicy }}
  labels:
    {{- include "extpdns-persist.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ $api_key }}
  tcp-control-secret: {{ $tcp_control_secret }}
  webserver-password: {{ $webserver_password }}
