{{- /* via https://github.com/helm/charts/issues/5167#issuecomment-641558251 */ -}}
{{- $key := (randAlpha 32) | quote }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace (include "extpdns-persist.fullname" .)) }}
{{- if $secret }}
{{- $key = index $secret.data "pdns-api-key" }}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "extpdns-persist.fullname" . }}
  annotations:
    "helm.sh/resource-policy": {{ .Values.persist.resourcePolicy }}
  labels:
    {{- include "extpdns-persist.labels" . | nindent 4 }}
type: Opaque
data:
  pdns-api-key: {{ $key }}
