# Default values for external-dns-power.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

resourcePolicy: keep

#  configuration for postgres object
pg:
  volumeSize: 192Mi
  instances: 2
  user: pdns-pdns-writer-user
  suffix: ".credentials.postgresql.acid.zalan.do"

# configures how main chart uses database
secret:
  suffix: "-persist"

pdns:
  service:
    api:
      appProtocol: http
      port: 80
      protocol: TCP
      #type: 
      #clusterIP:
    domain:
      appProtocol: domain
      port: 53
      protocol: UDP
      type: LoadBalancer
    domaintcp:
      appProtocol: domain
      port: 53
      protocol: TCP
    tcpcontrol:
      port: 53000
      protocol: TCP
  config:
    # allow-dnsupdate-from: "127.0.0.1/8, ::1"
    # any-to-tcp: "yes"
    api: "yes"
    # api-key: # secrets
    # api-readonly: "no"
    # api-logfile: /var/log/pdns-api.log
    # cache-ttl: 20
    # config-name:  # defined as extpdns.fullname in configmap
    disable-syslog: "yes"
    # default-api-rectify: "yes"
    # default-soa-edit: ""
    # default-soa-mail: ""
    # default-soa-name: ""
    # default-ttl: ""
    # distributor-threads: 3
    # dname-processing; "no"
    # dnsupdate: "no"
    # do-ipv6-additional-processing; "yes"
    # domain-metadata-cache-ttl: 60
    expand-alias: "yes"
    #gpgsql-host: {{ include "extpdns-persist.fullname" . }}
    gpgsql-dbname: pdns
    guardian: false
    # include-dir: # docker-pdns configures this
    launch: bind,gpgsql
    # load-modules:
    # local-address: "0.0.0.0, ::0"
    # local-address-nonexist-fail: "no"
    # local-port: 53
    # log-dns-details: "yes"
    # log-dns-queries: "yes"
    # log-timestamp: "yes"
    #loglevel: 4
    loglevel: 5
    # max-cache-entries: 1000000
    max-cache-entries: 10000 # small system configuration
    # max-packet-cache-entries: 1000000
    max-packet-cache-entries: 10000
    # max-queue-length: 5000
    # max-signature-cache-entries: # huge
    # max-tcp-connection-duration: 0
    max-tcp-connection-duration: 15
    # max-tcp-connections: 20
    max-tcp-connections: 200
    #max-tcp-connections-per-client: 0
    max-tcp-transactions-per-conn: 63
    # negquery-cache-ttl: 60
    negquery-cache-ttl: 5 # reduce memory pressure by lowering significantly
    # no-shuffle: "no"
    # non-local-bind: "no"
    # overload-queue-length: 0
    # query-cache-ttl: 20
    # query-local-address: "0.0.0.0, ::0"
    # query-logging: "no"
    # queue-limit: 1500 # ms
    # receiver-threads: 1
    # resolver: ""
    # recursive-cache-ttl: 10
    reuseport: "yes"
    # server-id: # set to extpdns.fullname in configmap
    # signing-threads: 3
    # socket-dir: "/run"
    tcp-control-address: 0.0.0.0
    tcp-control-range: "0.0.0.0/0,::0/0"
    # tcp-idle-timeout: 5
    tcp-fast-open: "32"
    # traceback-handler: "yes"
    # udp-truncation-threshold: 1232
    # version-string: full
    webserver: "yes"
    webserver-address: 0.0.0.0
    webserver-allow-from: "0.0.0.0/0;::0/0"
    # webserver-log-level: normal
    webserver-port: 80
    #xfer-max-received-mybtes: 100
    xfer-max-received-mybtes: 10
  image:
    repository: rektide/powerdns
    #pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"
    #pullSecrets: []

extdns:
  #domainFilters:
  #- yoyodyne.net
  #- example.com
  nameOverride: ""
  replicaCount: 1
  interval: 60s # semi-expensive to refresh so go slower
  logLevel: debug
  #owner: extdns-owner
  registry: txt
  source:
  - service
  - ingress
  image:
    repository: registry.opensource.zalan.do/teapot/external-dns
    #pullPolicy: IfNotPresent
    tag: "latest"
    #pullSecrets: []

replicaCount: 1

images:
  pullPolicy: IfNotPresent
  pullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service: {}
  # type: ClusterIP
  # clusterIP: "" # random
  # externalName: ""
  # type: ClusterIP
  # whatever else

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
