# Default values for external-dns-power.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#  configuration for postgres object
pg:
  resourcePolicy: keep
  volumeSize: 192Mi
  postgresInstances: 2

# configures how main chart uses database
persist:
  resourcePolicy: keep
  fullnameOverride: ""
  suffix: "-persist"
  db:
    user: pdns-pdns-writer-user
    suffix: ".credentials.postgresql.acid.zalan.do"

pdns:
  config:
    api: "yes"
    # api-logfile: /var/log/pdns-api.log
    gpgsql-host: {{ include "extpdns-persist.fullname" . }}
    gpgsql-dbname: pdns
    # log-dns-details: "yes"
    # log-dns-queries: "yes"
    launch: bind,gpgsql
    #loglevel: 4
    loglevel: 5
    # max-cache-entries: 1000000
    max-cache-entries: 10000 # small system configuration
    # negquery-cache-ttl: 60
    negquery-cache-ttl: 5 # reduce memory pressure by lowering significantly
    tcp-control-address: 0.0.0.0
    tcp-control-range: "0.0.0.0/0,::0/0"
    tcp-fast-open: "32"
    webserver: "yes"
    webserver-address: 0.0.0.0
    webserver-allow-from: "0.0.0.0/0;::0/0"
    webserver-port: 80
  image:
    repository: rektide/powerdns
    #pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"
    #pullSecrets: []

extdns:
  #domainFilters:
  #- yoyodyne.net
  #- example.com
  nameOverride: ""
  replicaCount: 1
  interval: 60s # semi-expensive to refresh so go slower
  logLevel: debug
  #owner: extdns-owner
  registry: txt
  source:
  - service
  - ingress
  image:
    repository: registry.opensource.zalan.do/teapot/external-dns
    #pullPolicy: IfNotPresent
    tag: "latest"
    #pullSecrets: []


replicaCount: 1

images:
  pullPolicy: IfNotPresent
  pullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 53

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
